name: Build ZMK firmware
on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      # This is the name of your build file, which is in your repo's root folder
      build_file: 'build.yaml'
